### ISSUE TITLE
Providing an official docker image at docker hub

### ISSUE THREAD

**Issue by a-powolozki** [WPS/egon.io#125]
**Is your feature request related to a problem? Please describe.**
When i want to run domain story modeler in docker, i have to clone the repo and call docker compose 

**Describe the solution you'd like**
My prefered way would be to pull an offical domain-story-modeler image from docker hub and simply run it, probably with additional parameters

**Describe alternatives you've considered**
nothing to add

**Additional context**
nothing to add

**Comment by johnholliday** [comment]
@a-powolozki In the meantime, you can create your own docker image as follows:

1. Install and run Docker Desktop on your host machine. 
2. Clone the repository and navigate to the project root folder.
3. Create a text file with the name 'Dockerfile' as follows:
```docker
FROM nginx
COPY . /usr/share/nginx/html
```
4. Create a 'docker-compose.yml' file in the root folder as follows:
```yaml
version: '3'
services:
  web:
    image: img-domain-story-modeler
    build: .
    container_name: domain-story-modeler
    restart: always
    ports:
      - "8080:80"
```
5. Open a terminal window in the project root folder and enter these commands:
```powershell
docker-compose build
docker-compose up -d
```

At this point, you will have a custom image containing a web server listening on port 8080 on your host machine.  To launch the app, open a browser and navigate to 'localhost:8080'.

If you are using Microsoft Edge, you can install this address as an App and then pin it to your start menu or taskbar so you can open it with a single click.

Hope this helps.
